### ISSUE TITLE
[BE] Set up GitHub Workflows for BudgetChain Backend

### ISSUE THREAD

**Issue by anonfedora** [BudgetChain/BudgetChain-Backend#5]
# Set up GitHub Workflows for BudgetChain Backend

## Issue Type
DevOps / CI-CD

## Priority
High

## Description
Implement comprehensive GitHub Actions workflows for the BudgetChain backend to ensure code quality, testing, and automated deployments across different environments.

### 2. Continuous Integration Workflow
- [ ] Create `ci.yml`:
```yaml
name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: budgetchain_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint
        
      - name: Type check
        run: npm run type-check
        
      - name: Run tests
        run: npm run test
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/budgetchain_test
          
```
